### ISSUE TITLE
Make slice error

### ISSUE THREAD

**Issue by jrots** [spiral/goridge#20]
got a weird error for a service that was already running for a week: 
when looking at the code it can only be triggered if leftBytes is negative? 
is that possible? 

data = make([]byte, 0, leftBytes)

```
panic: runtime error: makeslice: cap out of range
goroutine 89191655 [running]:
github.com/spiral/goridge.(*SocketRelay).Receive(0xc420142330, 0x0, 0x0, 0x0, 0x28, 0xc42047bda0, 0x0, 0x0)
        /Users/jayme/Documents/projects/go/src/github.com/spiral/goridge/socket.go:54 +0x20e
github.com/spiral/goridge.(*Codec).ReadRequestBody(0xc420346000, 0x0, 0x0, 0x0, 0x0)
        /Users/jayme/Documents/projects/go/src/github.com/spiral/goridge/codec.go:48 +0x48
net/rpc.(*Server).readRequest(0xc4201360a0, 0x93b520, 0xc420346000, 0x725fc0, 0x992af8, 0x93b520, 0xc420346000, 0x79a91f, 0x28, 0x0, ...)
        /usr/local/Cellar/go/1.9/libexec/src/net/rpc/server.go:547 +0xe1
net/rpc.(*Server).ServeCodec(0xc4201360a0, 0x93b520, 0xc420346000)
        /usr/local/Cellar/go/1.9/libexec/src/net/rpc/server.go:460 +0x77
net/rpc.ServeCodec(0x93b520, 0xc420346000)
        /usr/local/Cellar/go/1.9/libexec/src/net/rpc/server.go:669 +0x41
created by main.main
```

**Comment by wolfy-j** [comment]
Let me check, I guess this can be recent PR. Can you try using v2.0.3 ?

**Comment by wolfy-j** [comment]
Have you updated it? This have been recent update by contributor which passed all tests (including rr project) but who knows - https://github.com/spiral/goridge/commit/f0a8108aae0644682cff46536e9effabf18390d9

**Comment by wolfy-j** [comment]
I've made it protocol level error: https://github.com/spiral/goridge/releases/tag/v2.0.5
